
import java.util.TreeSet;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author damianchng
 */

//JFrame used for showing the ingredients checklist for a specific day. Shows prices of all ingredients in the day without any duplicates.
public class ChecklistPage extends javax.swing.JFrame {

    private Day day; //Specific day for checklist
    
    /**
     * Creates new form ChecklistPage
     * @param day
     */
    public ChecklistPage(Day day) {
        initComponents();
        //Ensures that program doesn't end when window is closed
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        //init day
        this.day = day;
        
        //Adding all ingredients from breakfast, lunch, and dinner to treeset
        TreeSet<Ingredient> ingChecklist = new TreeSet<>();
        if(day.getBreakfast() != null){
            ingChecklist.addAll(day.getBreakfast().getIngredients());
        }
        
        if(day.getLunch() != null){
            ingChecklist.addAll(day.getLunch().getIngredients());
        }
        
        if(day.getDinner() != null){
            ingChecklist.addAll(day.getDinner().getIngredients());
        }
        
        //update JList
        DefaultListModel mod = new DefaultListModel();
        for (Ingredient ingredient : ingChecklist) {
            mod.addElement(ingredient.toString() + "$");
        }
        checklist.setModel(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        checklist = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        title.setText("Checklist");

        checklist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(checklist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addComponent(title))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> checklist;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
